---
### Role Options
delete: true
install: true
delete_existing: false      # Delete LXC before installation if already existing
configure: true
start: false


### Proxmox API variables
proxmox_host: pve
proxmox_user: root@pam
proxmox_password: 12345
proxmox_node: pve
vmid: 999
hostname: test
root_password: 12345
os_type: auto
os_template: local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst
cores: 2
memory: 1024
swap: 0
net:
  name: eth0
  bridge: vmbr0
  ip: dhcp  # alternatively specify like: 192.168.1.222/24
  gw: ""    # alternatively specify like: 192.168.1.1
  mac_address: "" # alternatively spevify like: 02:00:00:12:34:56
dns_server: ""  # alternatively specify dns server like: 192.168.1.1
start_on_boot: false
timezone: Europe/Berlin
unprivileged: true
nesting: 0
keyctl: 0
ssh_pubkey: "{{ lookup('file', hostvars['localhost'].ssh_pub_key_path) }}"

# rootfs
rootfs_storage: local-lvm
rootfs_size: 8        # size in GB

# # additional mounts
# mounts:
#   - id: mp1
#     mountpoint: /mnt/data
#     size: 10
#     storage: local-lvm
#     #volume: lxc-{{vmid}}-disk-1  # must exist on the host if defined
    
#   - id: mp2
#     mountpoint: /mnt/media
#     size: 10
#     storage: local-lvm
#     #volume: lxc-{{vmid}}-disk-2  # must exist on the host if defined
    