---

- name: Start LXC container
  community.general.proxmox:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    node: '{{ proxmox_node }}'
    vmid: '{{ vmid }}'
    hostname: '{{ hostname }}'

    state: started
  when: not lxc_running
  delegate_to: localhost

- name: Set fact lxc_running
  set_fact:
    lxc_running: false


- name: Let it settle
  pause:
    seconds: 5